### ISSUE TITLE
Synagios: Build instructions and scripts

### ISSUE THREAD

**Issue by mclarkson** [mclarkson/nagrestconf#18]
Upload them!

**Comment by mhuettig** [comment]
Need build instructions for synagios/nagrestconf on Synology DS213+ (Freescale PowerPC syno-e500) and DS212+ (MARVELL Kirkwood 88F6282)

**Comment by mclarkson** [comment]
I don't have instructions for PowerPC since I don't have access to one but I have uploaded all of the files I use to build synagios. I have put them in the build directory in the root of the project.

The directory structure is as follows:
```
build
├── create_tgz
│   ├── build-arm
│   │   ├── create_tgz.arm.conf
│   │   ├── create_tgz.sh
│   │   └── synology
│   └── build-x86
│       ├── create_tgz.sh
│       ├── create_tgz.x86.conf
│       └── synology
├── doc
│   └── build.txt
├── synagios-arm
│   ├── INFO
│   ├── LICENSE
│   ├── PACKAGE_ICON_120.PNG
│   ├── PACKAGE_ICON.PNG
│   ├── scripts
│   │   ├── postinst
│   │   ├── postupgrade
│   │   ├── preinst
│   │   ├── preupgrade
│   │   └── start-stop-status
│   ├── tar_command.sh
│   └── WIZARD_UIFILES
│       └── install_uifile
└── synagios-x86
    ├── INFO
    ├── LICENSE
    ├── PACKAGE_ICON_120.PNG
    ├── PACKAGE_ICON.PNG
    ├── scripts
    │   ├── postinst
    │   ├── postupgrade
    │   ├── preinst
    │   ├── preupgrade
    │   └── start-stop-status
    ├── tar_command.sh
    └── WIZARD_UIFILES
        └── install_uifile
```
The build steps are in 'doc/build.txt'. I use this file to remind myself how to build.

I think I would try to build a powerpc chroot with debootstrap, copy it to the diskstation, then build synagios in the chroot. This is what I do with arm.

'create_tgz.sh' reads its configuration from 'create_tgz.\<arch\>.conf'.

Also, in the 'INFO' file, the 'arch=' line will need to have the arch added, probably 'qoriq'.

Good luck!

**Comment by mclarkson** [comment]
All build files are uploaded. Closing.
