### ISSUE TITLE
Synagios: Add nagios-nrpe-plugin to build

### ISSUE THREAD

**Issue by mclarkson** [mclarkson/nagrestconf#21]
The check_nrpe plugin is not installed and it should be.

**Comment by prsf1233** [comment]
Hi, thanks for the excellent port of Nagios. I would like to use check_nrpe but am unable to see the comment thread on how to set this up manually?

Regards
Graham

**Comment by mclarkson** [comment]
Enable console access in the DSM GUI (Control Panel -> Terminal & SNMP -> Enable SSH service).

Use putty or ssh to log into the diskstation, then paste the following:

```
chroot /volume1/@appstore/Synagios/nagios-chroot/ apt-get update
chroot /volume1/@appstore/Synagios/nagios-chroot/ apt-get install nagios-nrpe-plugin
```

Note that if you do:

    chroot /volume1/@appstore/Synagios/nagios-chroot/

then you will be in a standard debian wheezy system with standard nagios etc. So if you have ever used nagios on a debian system then [mostly] the same rules apply here, once you're chrooted in.

**Comment by prsf1233** [comment]
Perfect thanks!

From the command line it work fine:

root@DiskStation:/# ./usr/lib/nagios/plugins/check_nrpe -H 192.168.1.60 -c
check_plexmediaserver
PROCS OK: 5 processes with args 'plexmediaserver' | procs=5;;1:10;0;


I configured the command in the GUI:

$USER1$/check_nrpe -H $HOSTADDRESS$ -c check_plexmediaserver

However the service errors:

Status Information:Invalid host name '-c'


Any thoughts/suggestions?

Regards
Graham

**Comment by prsf1233** [comment]
It is now working, guess I was too impatient!

Thanks again
Graham

**Comment by mclarkson** [comment]
You're welcome :)

**Comment by mclarkson** [comment]
Added to build and will be in the next release.
