### ISSUE TITLE
when calling folders in a command that refernces windows servers I get an error 1028

### ISSUE THREAD

**Issue by cullenp** [mclarkson/nagrestconf#27]
When I enter either of the following commands I am given the:
ERROR 1028: 'folder' is undefined

Command #1 
check_nt_proc_mem

$USER1$/check_nt -H $HOSTADDRESS$ -p 12345 -v COUNTER -l "\\Process($ARG1$)\Working Set","Memory","Byte" -w $ARG2$ -c $ARG3$

Command #2 
check_nt_proc

$USER1$/check_nt -H $HOSTADDRESS$ -p 12345 -v COUNTER -l "\System\Processes" $ARG1$

**Comment by cullenp** [comment]
you can mark this as resolved.
Found that the \ character must be URL encoded to  %5C
$USER1$/check_nt -H $HOSTADDRESS$ -p 12345 -v COUNTER -l "%5CSystem%5CProcesses" $ARG1$

**Comment by mclarkson** [comment]
Glad you worked it out. Thanks.
