### ISSUE TITLE
Unable to install synagios_0.13_x86.spk on ds415+ DSM5.2

### ISSUE THREAD

**Issue by marco509** [mclarkson/nagrestconf#30]
![syno](https://cloud.githubusercontent.com/assets/11209068/6389141/8f2a6a0a-bda1-11e4-8745-8386cf9715a9.JPG)
 Dear,

I wanted to test your nagios solution on synology and i ve an error message on the synology whose said : the package is not compatible 

Do you know wants happen?

regards

**Comment by mclarkson** [comment]
Looks like I'll need to find the platform code for your device and add it to the synology installation script.
I'll try and take a look tonight.

By any chance, have you downloaded any other .spk files that do work on your synology box?
If so, can you provide the name and or link so I can download the same one and 'steal' their codes.

Thanks for the report!

**Comment by marco509** [comment]
if it can help you, this one works ..

http://minimserver.com/downloads/index.html 	MinimServer-0.8.3b-x86.spk

**Comment by mclarkson** [comment]
Thanks for that - I will take a look.

**Comment by Toorop55** [comment]
Hello, same issue with DS414j (ARM plateform)

**Comment by mclarkson** [comment]
Thanks for the report @Toorop55. Do you know / are you able to check, if http://minimserver.com/downloads/index.html works on your synology box?

**Comment by Toorop55** [comment]
Yes, Minimserver works on my DS414j.

**Comment by mclarkson** [comment]
Hi @marco509 @Toorop55 
I've put two new synology spk packages on sourceforge:

  x86 - [synagios_0.13_installfix_x86.spk](http://sourceforge.net/projects/nagrestconf/files/Synology/x86/synagios_0.13_installfix_x86.spk/download)
  arm - [synagios_0.13_installfix_arm.spk](http://sourceforge.net/projects/nagrestconf/files/Synology/arm/synagios_0.13_installfix_arm.spk/download)

Hopefully this allows you both to install synagios.

**Comment by marco509** [comment]
Thank you very much, the installation works fine now.

Have e good week end
