### ISSUE TITLE
nagrestconf is weak, why not using adagios

### ISSUE THREAD

**Issue by zimmerlis** [mclarkson/nagrestconf#32]
Synagios is great, but when I have started to work with it I am missing two features:

1. I cannot change the Linux icon when using nagrestconf.
2. I cannot scan the network to auto discover all hosts on the network.

It looks like adagios is a better configuration interface.

How can I add this in the chroot environment of synagios?

**Comment by mclarkson** [comment]
Issue #22 might help for changing the Linux icon to something else.
Auto-discovery could be done either by a new plugin, or by using nmap and the rest interface. This could be useful if an nmap+REST script were run periodically, thereby finding new hosts, and possibly deleting or disabling old hosts. I quite like the sound of that for a home network.

You can do something like:
```
cd /volume1/@appstore/Synagios/nagios-chroot
chroot .
```
Then use instructions for installing adagios on Debian. It should work fine, and follows very similar design principles to nagrestconf.
