### ISSUE TITLE
https access to services in Synagios package for Synology

### ISSUE THREAD

**Issue by juanyque** [mclarkson/nagrestconf#34]
Hi,

I have added https access to services nagios3 and nagrestconf with this method:

== Configure https ==

* Go to apache2 config files in Synagios package:

 {{{cd /volume1/@appstore/Synagios/nagios-chroot/etc/apache2/sites-enabled}}}

* Copy available conf file for ssl:

 {{{cp ../sites-available/default-ssl .}}}

* Change port 443 for desired one (4443 in this case):

 {{{vi default-ssl}}}
{{{
...
\<VirtualHost _default_:4443\>
...
}}}

== Enable https ==

* Whit service ''Synagios'' launched (then ''dev'', ''proc'', ''sys'' are mounted), launch a shell in chroot environment:

 {{{chroot /volume1/@appstore/Synagios/nagios-chroot /bin/bash}}}

* Enable ssl in apache2:

 {{{a2enmod ssl}}}

* Restart apache:

 {{{/etc/init.d/apache2 restart}}}

* Exit from chroot envifonment:

 {{{exit}}}

**Comment by mclarkson** [comment]
Hi,
This is really useful information, thanks! If you have a blog page then it would be great to link to it from the nagrestconf web site with this info. Otherwise I will add this info to my blog and link to that instead. Let me know.

Cheers
Mark.

**Comment by mclarkson** [comment]
I put this on my blog [here](http://blogger.smorg.co.uk/2015/09/synagios-enabling-https-for-nagrestconf.html). Thanks Juan.

**Comment by juanyque** [comment]
Thanks! sorry for never respond... recovering my live 😅
