### ISSUE TITLE
Nagrestconf & Nagios3 Error

### ISSUE THREAD

**Issue by fl0wx** [mclarkson/nagrestconf#37]
Hey i installed synagios with the installfix spk. After this i got always the same error if i try to add anything to nagrestconf: "NAGCTL ERROR: Invalid data. A required field is empty." 

If i try to open nagios3 and navigate to hosts i got following error:

Whoops!

Error: Could not read object configuration data!

Here are some things you should check in order to resolve this error:

Verify configuration options using the -v command-line option to check for errors.
Check the Nagios log file for messages relating to startup or status data errors.
Make sure you read the documentation on installing, configuring and running Nagios thoroughly before continuing. If all else fails, try sending a message to one of the mailing lists. More information can be found at http://www.nagios.org.

Any ideas?

**Comment by mclarkson** [comment]
Uninstall it, then install it again and ensure to restore the configuration from the section:

> [optional] Restore the sample backup configuration

from the [installation documentation](http://nagrestconf.smorg.co.uk/installguides/synology.php).

**Comment by fl0wx** [comment]
Thank you a lot. Nagrestconf is now working. but in nagios 3 it keeps saying 

Whoops!

Error: Could not read object configuration data!

**Comment by fl0wx** [comment]
But how can i use for example aNag (android nagios Client) for synaios? i have to tell him a nagios cgi folder. where can i find this in your package

**Comment by mclarkson** [comment]
Take a look at Issue #34
