### ISSUE TITLE
Custom Object Variables for the host

### ISSUE THREAD

**Issue by pbtesoroni** [mclarkson/nagrestconf#38]
Please add a custom variable for the host. I need to add a macro for volumes and instance ID for my aws monitoring.

**Comment by mclarkson** [comment]
Good timing - I'm hoping to get a new release out over the weekend so I will try to squeeze this in.

**Comment by mclarkson** [comment]
I just noticed that I don't have custom variables in REST for the host, only for services.

Is it for a nagios plugin? Could you use a service custom variable? For something like 'check_ec2 $_SERVICEINSTANCEID$', or 'check_ec2_volume $_SERVICEVOLNAME', rather than using HOST custom vars.

If you need it for the host then it might not be until the release after next.

I didn't realise I had missed this nagios option :(

**Comment by pbtesoroni** [comment]
The problem is I need this to work with the REST API. we are making an environment that when a user creates an instance it will  automatically input the host information <including their Instance ID and Volume ID>in the config file. These instances could be created and erased several times,so by using the RESTapi it will add the _INSTANCE_ID and _VOLUME string to the host information so I don't have to change the service string every time the Instance and Volume ID changes.

 < for example>

define command {
	command_name	check_ec2_status
	command_line	RUBYOPT="rubygems" $USER11$/check_ec2_status.rb -a $HOSTADDRESS$ -i $_HOSTINSTANCE_ID$ -f $USER6$
}

OR

define command {
        command_name    check_cloudwatch_status
        command_line    RUBYOPT="rubygems" $USER11$/check_cloudwatch_status-2.5.07.rb -a $HOSTADDRESS$ -i $_HOSTINSTANCE_ID$ -f $USER6$ -C $ARG1$ -c $ARG2$ -w $ARG3$

The host information will look like:

Define host {
	host_name server
        use home
        address 454.454.454.454
	_instance_id i-er9djwf
	_volume vol-f39572c
        check_command check_ec2_status!$_HOSTINSTANCE_ID$!$USER6$
        max_check_attempts 3
	}

Understand what I'm saying?

If your software can't do this can you think of another way of doing this. I can't find another other RESTapi for Nagios that will add host information and erase host information.

**Comment by mclarkson** [comment]
Yep, that makes sense. Thanks for the extra info.

As a workaround you could use service custom vars since it's only one extra call, but I can definitely see why you would rather change host custom vars.

I'll add custom vars for hosts and put it in the next release. Let me know your platform and I'll release that first.

**Comment by pbtesoroni** [comment]
Thanks! I'm using Ubuntu. Would you happen to know when the next release could be? If I give me manager a timeframe of when this will be added I could go forward with this... if not I will see what I can do with your suggestion.

**Comment by mclarkson** [comment]
Sometime next week is the best I can say. I'll test it on Ubuntu Trusty.

**Comment by pbtesoroni** [comment]
Great!! Thank you!! Also I know I should be adding this to a new issue but
would it be possible to use a dns name instead of the ip address in the
host information?

**Comment by mclarkson** [comment]
Someone else requested that so I added issue #25, which is resolved now, and will also be in the next release :)

**Comment by mclarkson** [comment]
There's a new release, 1.174, on sourceforge for Ubuntu Trusty, which is available in the [downloads section](http://nagrestconf.smorg.co.uk/downloads.php) of the Web site. Thanks for the nudge :)

The REST api now supports host custom variables and the GUI has fields for custom variables and notes. Plus there's a bunch of other fixes and enhancements.

The custom variable would look like `_instance_id|i-er9djwf,_volume|vol-f39572c`. It's shown as a compound variable in the [REST reference](http://nagrestconf.smorg.co.uk/documentation/restreference.php) docs. Not pretty but it works. Adding a note such as `Instance ID: $_HOSTINSTANCE_ID$ .. Volume: $_HOSTVOLUME$` will show the custom variable in the host details nagios page, for verification.

NOTE: The custom variable is not url encoded, so many special characters cannot be used.

I tested the installation in Ubuntu Trusty a few times and updated the [Ubuntu Installation Docs](http://nagrestconf.smorg.co.uk/installguides/ubuntu.php), which are now a little shorter and actually work! The last version I tested was Saucy but not much has changed in Trusty.

Let me know if you have any problems.

**Comment by pbtesoroni** [comment]
That’s awesome news!!! Since I already have the original version configured
do I just do a backup and then follow the same directions and then restore?



Thanks,



Brian Tesoroni



Infrastructure

Provenir, Inc.

973.316.8680



*From:* Mark Clarkson [mailto:notifications@github.com]
*Sent:* Thursday, September 10, 2015 8:22 PM
*To:* mclarkson/nagrestconf <nagrestconf@noreply.github.com>
*Cc:* pbtesoroni <btesoroni@provenir.com>
*Subject:* Re: [nagrestconf] Custom Object Variables for the host (#38)



There's a new release, 1.174, on sourceforge for Ubuntu Trusty, which is
available in the downloads section
<http://nagrestconf.smorg.co.uk/downloads.php> of the Web site. Thanks for
the nudge :)

The REST api now supports host custom variables and the GUI has fields for
custom variables and notes. Plus there's a bunch of other fixes and
enhancements.

The custom variable would look like
_instance_id|i-er9djwf,_volume|vol-f39572c. It's shown as a compound
variable in the REST reference
<http://nagrestconf.smorg.co.uk/documentation/restreference.php> docs. Not
pretty but it works. Adding a note such as Instance ID: $_HOSTINSTANCE_ID$
.. Volume: $_HOSTVOLUME$ will show the custom variable in the host details
nagios page, for verification.

NOTE: The custom variable is not url encoded, so many special characters
cannot be used.

I tested the installation in Ubuntu Trusty a few times and updated the Ubuntu
Installation Docs <http://nagrestconf.smorg.co.uk/installguides/ubuntu.php>,
which are now a little shorter and actually work! The last version I tested
was Saucy but not much has changed in Trusty.

Let me know if you have any problems.

—
Reply to this email directly or view it on GitHub
<https://github.com/mclarkson/nagrestconf/issues/38#issuecomment-139417080>.

**Comment by mclarkson** [comment]
Do a backup, get the new .debs, and `dpkg -i ..` them. That should be it. Should be no need to restore.

I had to add a new field to hosts for this 'fix', and in the past, when adding multiple new fields, there was an update script to migrate the csv files. I don't think that's necessary in this case with only one field added. Seems to work fine for me but something to be aware of. Doing a restore will correct files from a previous version though. If you want to do a restore just delete all entries in the hosts table, and then only restore the hosts table from the backup. This will ensure the correct format since no other tables have changed.
