### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by maestrx** [mclarkson/nagrestconf#39]
I've just installed latest version v1.174.1 of the Nagrestconf and I'm getting following errors in the Firefox debug console when showing the GUI http://127.0.0.1/nagrestconf/index.php?tab=2:

GET 
http://10.50.25.2/nagrestconf/images/ui-bg_flat_75_ffffff_40x100.png [HTTP/1.1 404 Not Found 5ms]
GET 
http://10.50.25.2/nagrestconf/images/ui-bg_highlight-soft_75_cccccc_1x100.png [HTTP/1.1 404 Not Found 5ms]
GET 
http://10.50.25.2/nagrestconf/images/ui-bg_glass_75_e6e6e6_1x400.png [HTTP/1.1 404 Not Found 10ms]
GET 
http://10.50.25.2/nagrestconf/images/ui-bg_glass_65_ffffff_1x400.png [HTTP/1.1 404 Not Found 5ms]

I can see that the images are part of the rpm delivery, but in "unexpected" directory. I've tried to fix it by running "ln -s /usr/share/nagrestconf/htdocs/nagrestconf/css/redmond/images/*.png /usr/share/nagrestconf/htdocs/nagrestconf/images/", but the expoectd images are not tehre either :)

Thanks
Vit

**Comment by maestrx** [comment]
Download of the zip file https://jqueryui.com/resources/download/jquery-ui-1.10.3.zip, extracting it somewhere and copying using "cp jquery-ui-1.10.3/themes/base/images/* /usr/share/nagrestconf/htdocs/nagrestconf/images" fixed the issue, but there are still some GUI inconsistencies and the theme is grey, not blue like on screenshots. Intentionally?

**Comment by mclarkson** [comment]
What distribution are you using?

**Comment by maestrx** [comment]
Rhel6
Dne 16. 9. 2015 19:21 napsal uživatel Mark Clarkson <notifications@github.com>:What distribution are you using?

**Comment by mclarkson** [comment]
According to http://www.w3.org/TR/REC-CSS1/#url and http://www.w3.org/TR/CSS21/syndata.html#uri, "Partial URLs are interpreted relative to the source of the style sheet, not relative to the document". So your browser has no business looking in `/images/`, it should be looking in `css/redmond/images/`.

The CSS stylesheet is declared in `/usr/share/nagrestconf/htdocs/nagrestconf/index.php`, exactly as:

```
<link rel=stylesheet type=text/css
    href=css/redmond/jquery-ui.css />
```

Maybe that CSS is not formatted correctly for your browser, or your browser is not interpreting the CSS standard correctly.

So, what Web Browser are you using? Can you try a different one?

**Comment by mclarkson** [comment]
I just noticed you said "Firefox debug console". All my testing is done in Firefox, and has been for years. I'm confused! I just tried uninstalling then reinstalling nagrestconf again and I can't replicate the problem.

I suggest trying a fresh install of Chrome if you don't use it already to see if that works as the Browser is simply asking for the wrong file.

**Comment by maestrx** [comment]
oh my... :+1: indeed you are right! Using FF 40.0.3 is not working, but in IE11 and Chrome 45.0 works like a charm :)

Thanks and sorry for the wasted time...

**Comment by maestrx** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/6150459/9917950/97c4b040-5cc4-11e5-9caf-c6c06fff7dc8.png)

**Comment by maestrx** [comment]
Ok, thanks to your inputs I've found the reason... Greasemonkey plugin. When disabled all works just fine...

**Comment by mclarkson** [comment]
Thanks for reporting the problem anyway. Good to know!
