### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maestrx** [mclarkson/nagrestconf#40]
Is there a way to "force delete host" including all linked services at once? Currently I need to delete all linked services using:
POST /delete/services $PS',"name":"EWD431-O2CZ_INT_APP2-jkadanik","svcdesc":".*"'$PE
before I can do 
POST /delete/hosts $PS',"name":"EWD431-O2CZ_INT_APP2-jkadanik","svcdesc":".*"'$PE
Otherwise I get error: ["NAGCTL ERROR: Host is referenced by one or more services. Will not delete."]
Host/services created using:
POST /add/hosts $PS',
     "name":"EWD431-O2CZ_INT_APP2-jkadanik",
     "alias":"1298",
     "ipaddress":"xxx",
     "template":"generic-host",
     "hostgroup":"vm",
     "contact":"vsafar"
'$PE
POST /add/services $PS',
     "name":"EWD431-O2CZ_INT_APP2-jkadanik",
     "template":"generic-service",
     "command":"check_ssh",
     "svcdesc":"SSH"
'$PE
POST /add/services $PS',
     "name":"EWD431-O2CZ_INT_APP2-jkadanik",
     "template":"generic-service",
     "command":"check_ping",
     "svcdesc":"PING"
'$PE

In general I had quite a lot of troubles to perform initial setup of the environment. For example why are templates mandatory for hosts/services? 

Thanks

**Comment by mclarkson** [comment]
No there isn't, sorry. See 'Delete a host' in [the REST Cookbook](http://nagrestconf.smorg.co.uk/documentation/restcookbook.php).

There is an example configuration to take the pain out of the initial configuration and there is also an example script that sets everything up from scratch using rest. Generally, an initial configuration would start from the right-most tab and end at the left-most tab.

There is an example configuration to take the pain out of the initial configuration and there is also an example script that sets everything up from scratch using rest. Generally, an initial configuration would start from the right-most tab and end at the left-most tab.

Consider using service sets to avoid adding services manually. Using this method will allow a host to be added in one line of REST in a script, by specifying one or more service sets in the GUI when adding a host, or by providing a CSV file with the same information for bulk setup of hosts.

In the GUI there are many options that are unavailable for hosts that are only available by changing the templates. When I initially wrote the REST interface only a small subset of nagios options were available as it was built to do a specific task, following some simple rules. These rules were there to help with scalability and to provide a minimum viable product. For instance, host or service contacts should really be supplied in templates to keep things manageable, but can be overridden for special cases. For larger environments there are often a number of servers requiring identical monitoring configuration and in these cases service sets can really help.  After many years configuring nagios the rules I have found that work well are reflected in the UI. For small environments it may make things harder at the start, but would make it easier to scale later on. Also bear in mind that it was designed for a large environment with a Network Operations Centre in India with many sys admins able to configure many nagios instances located centrally and some remotely, but with a single display console. This set up is not explained, but the system is designed for it, for example, hosts can be put into testing mode for initial set up, so they are not seen at the NOC until all services are 'green'. Testing mode has no effect for a single Nagios server.

I think that a lot more documentation is needed to help new users, or for evaluation. Would some good documentation have have made it less painful do you think? Would you have read it? (I have Ansible's style of documentation in mind as that got me going with it pretty quickly.)

**Comment by maestrx** [comment]
Wow. Thanks a bunch for the explanation. 

I believe you should put the text above somewhere on the top of the documentation page. I understand the mindset of the design now and its clear how to achieve the target. I like the servicesets, though have to check if I can assign individual contact group for each host having the same serviceset. 

You usually recognize a great tool that will ease your life, like this one. In such cases you read a whole documentation as you need to have a way how to asses the feasibility of the tool and evaluate how it fits your expectations/possibilities.

I'm going to create a Python 2.x binding, interested in sharing it?
I need the recheck feature to be implemented, but not sure how to do on github... I'll try to share :)

THX

**Comment by mclarkson** [comment]
I would certainly place a link in the Web site to your GitHub page, Blog post, whatever, to a python binding. Would be great - especially if it did the url encoding for the fields that require it, as marked in the [REST Reference document](http://nagrestconf.smorg.co.uk/documentation/restreference.php).
