### ISSUE TITLE
Documentation bug: service contacts API

### ISSUE THREAD

**Issue by maestrx** [mclarkson/nagrestconf#42]
Hello,

when creating services on host and specifying "contact" in the API, I don't see the value in the GUI for the service. The parameter for the service add is specified on the docs page "http://nagrestconf.smorg.co.uk/documentation/restreference.php#_commands"/ 1.2.4 Hosts / 6. Contacts / REST variable name states parameter name "contact". When changed the client to pass parameter contacts, it started to work :)

BR

**Comment by mclarkson** [comment]
The code is out of sync with itself too. Contacts is set using 'contacts', but when querying (/show/hosts) it shows 'contact'. Not sure if anyone will rely on it staying as 'contact' so now I'm scared to correct it. I guess I should leave it until a major version change.

I'll correct the doc though, and "Note: When using '/show/hosts' the contacts field is output as 'contact', without the 's', but set with 'contacts', with the 's'.".

Thanks for reporting.
