### ISSUE TITLE
Host update via GUI

### ISSUE THREAD

**Issue by maestrx** [mclarkson/nagrestconf#44]
Hi, 

when trying to update host via GUI (change IP for example), I get following error:
NAGCTL ERROR: Service Set '-' not found. Will not modify host.

In case I check the "Re-apply Service Sets"  I'm able to save the modification of the host but I loose all services assigned to the host... :) 

Any idea why/what I can do to fix this?

Thanks
Vit

**Comment by mclarkson** [comment]
Thanks for that. Use the sed line (if you are able to copy and paste), or manually edit; both shown below.

```
sed -i '/modify_host_line()/,/^}/ {s/\[\[ -n $servicesets \]\] && {/[[ -n $servicesets \&\& $servicesets != "-" ]] \&\& {/}' /usr/bin/nagctl
```
Find the `modify_host_line` function in `/usr/bin/nagctl` and within the function change the line:
```
[[ -n $servicesets ]] && {
```
to:
```
[[ -n $servicesets && $servicesets != "-" ]] && {
```

**Comment by mclarkson** [comment]
Assuming fixed.

**Comment by maestrx** [comment]
Bug fix confirmed, Thanks
