### ISSUE TITLE
No Nagios service restart after restart request

### ISSUE THREAD

**Issue by woulf** [mclarkson/nagrestconf#50]
I'm using a dockerised version of nagrestconf, based on debian:jessie.
the packages used are thoses:

    root@79c43e1907d6:/tmp# ls -l
    total 716
    -rw-r--r-- 1 nagios nagios      0 Dec  8 11:20 nagios_restart_request
    -rw-r--r-- 1 root   root    13544 Oct 13 11:52 nagrestconf-backup-plugin_1.174.2_all.deb
    -rw-r--r-- 1 root   root    15264 Oct 13 11:52 nagrestconf-services-plugin_1.174.2_all.deb
    -rw-r--r-- 1 root   root   699624 Oct 14 19:06 nagrestconf_1.174.2_all.deb

when i manually launch /usr/bin/restart_nagios nagios is effectivelly restarted, but when i do a rest, or webadmin, restart the service isn't restarted, even after 15min.

as you can see on the ls -l output i have an empty "nagios_restart_request" in /tmp
my crontab is like this:

    # DO NOT EDIT THIS FILE - edit the master and reinstall.
    # (- installed on Tue Nov 10 15:46:49 2015)
    # (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
    * * * * * /usr/bin/test -e /tmp/nagios_restart_request && ( /bin/rm /tmp/nagios_restart_request; /usr/bin/restart_nagios; )

The checkexternalcommand in nagios.cfg is at 1
and .conf files for restart_nagios and nagctl seems ok
any idea what could be wrong?

**Comment by mclarkson** [comment]
Nagrestconf in a Docker container - that's great!

Probably crond is not running in the container. [Baseimage docker](https://github.com/phusion/baseimage-docker) might fix it if that's the case.

Is it publicly available? If so, I'd like to give it a go :)

**Comment by woulf** [comment]
It seems to be that,
i'll check after some other debug.

it's not publicly available since that's a pretty specific image (fixed host, ndo2db without local mysql server, no port exposed on host).

I hope i will be able to do a generic image soon anyway :)

**Comment by woulf** [comment]
Yep everything working as expected now!
Instead of changing the image i just added a new service (cron -f -l) to my runit services.

thanks!

**Comment by mclarkson** [comment]
Great! Let me know if you do create a public image so I can put a note up about it.
