### ISSUE TITLE
Debian fresh installation steps does not install Nagios web UI

### ISSUE THREAD

**Issue by thoopes** [mclarkson/nagrestconf#51]
Installing with Debian 'Jessie' and following the documentation produces a 'working' nagios instance (back-end) and nagrestconf web interface, but I do not have a /nagios directory where apache would be looking for it -- in other words, I do not have a nagios web interface.  Does anything additional need to be done to fix this?  Or did I miss something?

"404 - not found
The requested URL /nagios was not found on this server."

It looks like everything is working (within /nagrestconf) for localhost monitoring after importing the sample config...

**Comment by mclarkson** [comment]
On Jessie it's /nagios3

**Comment by mclarkson** [comment]
I've just updated the installation docs to say that. Thanks!

**Comment by thoopes** [comment]
Thank you!
