### ISSUE TITLE
Only one parent in host definition possible

### ISSUE THREAD

**Issue by cmdrtom** [mclarkson/nagrestconf#53]
Hi,

how I can insert two parents in host definition. When I insert two valid hosts the configuration shows fail: "parent host hostA hostB is not valid".

**Comment by mclarkson** [comment]
Sorry, it's a bug.

To fix edit /usr/bin/csv2nag and change from line 661:
```
        [[ -n $parents ]] && {
            Echo "       parents $parents"
        }
```
to
```
        [[ -n $parents ]] && {
            t="${parents// /,}"
            Echo "       parents $t"
        }
```

**Comment by cmdrtom** [comment]
Great! It works perfect.

**Comment by cmdrtom** [comment]
Thanks.

**Comment by mclarkson** [comment]
You're welcome.
I'll leave this open until it's fixed in the source.
