### ISSUE TITLE
renaming pretty much anything

### ISSUE THREAD

**Issue by btesoroni** [mclarkson/nagrestconf#54]
I'm looking to see if you would be able to add a feature.. I would love to be about to rename host groups or pretty much rename anything. Would that be possible?

**Comment by mclarkson** [comment]
Generally, clone or create new items then relink to them.

So, for example, to change a hostgroup, 'app', to 'legapp', would involve:

1. Groups Tab - Create a new 'legapp' hostgroup
2. Hosts Tab - Filter by 'app' hostgroup
3. Click Bulk Tools. Bulk Tools will operate on all items shown.
4a. 'Field to change' - choose 'hostgroup'
4b. 'Change action' - choose 'replace'
4c. 'Text' - type 'legapp', then Apply Changes

The 'app' hostgroup can now be deleted. If any items are still left in the app group then it won't allow it to be deleted.

To change a host name you would clone the host using the GUI. The same goes for servicesets.

Likewise, to change the name of a service you would clone the service using the GUI, and clone it to the same host with a different service name. Then delete the old one.

All the above can be completed using shell scripts and *nrcq* or *curl* for much finer control. So, for example, below is a script that will change any hostgroup name.

```bash
#!/bin/bash

orig_hgname=$1
new_hgname=$2
description=$3
URL="http://10.11.12.10:8888/rest"

[[ -z $1 || -z $2 || -z $3 ]] && {
  echo "Change a hostgroup name."
  echo "Usage: `basename $0` old_name new_name description"
  exit 1
}

# Make sure orig_hgname exists
h=`nrcq $URL show/hostgroups -f "name:\b$orig_hgname\b"`
[[ -z $h ]] && {
  echo "Hostgroup, '$orig_hgname', does not exist."
  exit 1
}

# Make sure new_hgname does not exist
h=`nrcq $URL show/hostgroups -f "name:\b$new_hgname\b"`
[[ -n $h ]] && {
  echo "Hostgroup, '$new_hgname', exists!"
  exit 1
}

# Add the host group
nrcq $URL add/hostgroups -d "name:$new_hgname" -d "alias:$description"

# Change existing hosts that have old_name in the hostgroup

hosts=`nrcq $URL show/hosts -f hostgroup:legapp | sed -n 's/^ *name://p'`

for host in $hosts; do
  echo nrcq $URL modify/hosts -d "name:$host" -d "hostgroup:$new_hgname"
  nrcq $URL modify/hosts -d "name:$host" -d "hostgroup:$new_hgname"
done

# Delete the old hostgroup
nrcq $URL delete/hostgroups -d "name:$orig_hgname"

```
The script could be used to change 'legapp' back to 'app', by:
```
bash change_hostname.sh legapp app "App Servers"
```

**Comment by mclarkson** [comment]
Documentation added to the [REST Cookbook](http://nagrestconf.smorg.co.uk/documentation/restcookbook.php). Please re-open if this does not address your issue.

Thanks for your feedback!
