### ISSUE TITLE
restAPI and Service Set field

### ISSUE THREAD

**Issue by btesoroni** [mclarkson/nagrestconf#60]
Through the nagrestconf GUI, when we edit the host, we have the option to “Re-apply Service Sets”. I found this is the only effective way you can clear (set to empty) the Service Sets field of a host is if you also have this box checked when clicking Apply Changes.
 
When trying to modify a host through the nagrestconf REST API, I can change the Service Sets easily to another valid value, but I cannot clear it / set it to empty. Is there a way to do this through the REST call? I don’t see any option jumping out at me to be able to set the Re-apply Service Sets to true while modifying a host.

**Comment by mclarkson** [comment]
For me, if I click 'Edit Host', delete contents of the 'Service Sets' field, and click 'Apply Changes' then the Service Set field is cleared and the data files are updated correctly.

I'm using version 1.174.5 - maybe you're using an older version?

**Comment by btesoroni** [comment]
I tried to upgrade but I got this error:

ERROR: Conf nagrestconf not properly enabled:
/etc/apache2/conf-enabled/nagrestconf.conf exists but does not point to
/etc/apache2/conf-available/nagrestconf.conf, not touching it
dpkg: error processing package nagrestconf (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 nagrestconf

**Comment by btesoroni** [comment]
I still cannot do this through the REST API. When attempting to clear the
Service Sers field through a modify/hosts REST command, I tried sending:



"servicesets":" "

and

"servicesets":""

And

leaving out the field all together…



but the servicesets are never cleared when reviewing from the GUI. Changing
the servicesets field to another valid value works, but I still can’t
figure out how to clear it with the REST API call.

**Comment by mclarkson** [comment]
If you managed to upgrade then with the REST API fields are deleted with a minus sign, '-'.
```
"servicesets":"-"
```
This info is in the Modify a Host section in the [rest tutorial](http://nagrestconf.smorg.co.uk/documentation/resttut.php).

**Comment by mclarkson** [comment]
If you didn't manage to upgrade then correct the error and try again. In this case:

```
/etc/apache2/conf-enabled/nagrestconf.conf exists but does not point to /etc/apache2/conf-available/nagrestconf.conf
```
so should be something like:
```
mv /etc/apache2/conf-enabled/nagrestconf.conf ~
ln -s /etc/apache2/conf-available/nagrestconf.conf /etc/apache2/conf-enabled/nagrestconf.conf
```

**Comment by btesoroni** [comment]
I still have one more problem with the REST API.
First, I did try the "-" option to delete the servicesets from a host
during a modify operation, and that worked just fine. He says it is in the
REST API documentation, but I couldn't find it anywhere here:
http://nagrestconf.smorg.co.uk/documentation/restreference.php

I still have the problem of triggering the whole "Re-apply server sets"
after I edit / remove them from a host. How can I do this with a REST call?
I can't find it anywhere in the documentation

**Comment by mclarkson** [comment]
Good point. I guess it should be in the reference page too (It's in the REST Tutorial). I'll have to think about it though, if I put it there then will I have to put other documentation in there too? Most likely I'll put it in that page; if you looked there for it then others will too. Thanks for that.

I think maybe the information on service sets isn't clear. Have a read of http://blogger.smorg.co.uk/2014/02/nagrestconf-service-sets.html to get an idea about service sets (sorry if you know already!), then let me know what it is you're trying to do - maybe with your code too...

**Comment by mclarkson** [comment]
I just reread your last message and it seems quite clear today (it didn't yesterday!). There is no rest call to re-appy a service set. The GUI deletes the host then creates it from scratch. Look in the Cookbook page to see how to delete a host, then the tutorials page to see how to add one - but add it with the serviceset field set.

**Comment by mclarkson** [comment]
The only time a service set is applied is when a host is created. No other time does it happen.

**Comment by mclarkson** [comment]
Assuming issue is solved. Re-open if required.
