### ISSUE TITLE
New enhancement request: Host template custom vars support

### ISSUE THREAD

**Issue by lucasmartinez** [mclarkson/nagrestconf#62]
Hi. I see you don't have custom vars for host templates.
We organice our hosts using custom vars like a Tree hosts as follows:

define host {
	name                           	ARGENTINA
	_PAIS                          	ARGENTINA
	register                       	0
}

define host {
	name                           	BRASIL
	_PAIS                          	BRASIL
	register                       	0
}

define host {
	name                           	BSAS
	use                            	ARGENTINA
	_UNIDAD_NEGOCIO                	BUENOS AIRES
	register                       	0
}

define host {
	name                           	ROSARIO
	use                            	ARGENTINA
	_UNIDAD_NEGOCIO                	ROSARIO
	register                       	0
}

define host {
	name                           	RIO
	use                            	BRASIL
	_UNIDAD_NEGOCIO                	RIO DE JANEIRO
	register                       	0
}

Then, we use ROSARIO , BSAS or RIO in out host definitions files:

define host {
	host_name                      	XTM_AR_BSAS
	alias                          	XTM_AR_BSAS
	use                            	BSAS
	check_command                  	check_host_alive!300.0,80%!500.0,100%!4
        .........

Finally, we will have _PAIS and _UNIDAD_NEGOCIO in the generated host by inheritance.

We are unable to resolve this situation because you don't have support for custom vars in host templates.

Alse we found that you have required fields like checkinterval, retryinterval, notifperiod, checkperiod, etc. for hosttemplates but those fields are not required by nagios so Is there any way to remove that restriction when creating host templates ?

Best Regards

**Comment by mclarkson** [comment]
This all makes sense. It's a fair chunk of work to implement custom variables for hosts/hosttemplates, but it needs to be done.

I'm not sure about removing the required fields though. I think the last time I looked at this it made the host checking quite difficult - so it wasn't worth the effort. I'll have another look at this though as it would be nice to remove the restriction.

**Comment by mclarkson** [comment]
This is now implemented and looks good in my tests. [Nrcq]( https://github.com/mclarkson/nrcq) and the [go library](https://github.com/mclarkson/nagrestconf-golib) were updated too since an extra field was added. What OS are you using so I can build 1.174.7 for that first?

**Comment by lucasmartinez** [comment]
I'm using suse sle 11. I hace installed by hand. So dont worry. I Will Download objects manually.

**Comment by mclarkson** [comment]
Ok, great! You installed by hand!!! Did you try the CentOS rpms? I have no idea if they would work or not. Would it take much to modify spec file for suse?

**Comment by mclarkson** [comment]
Assuming issue is resolved. Re-open if necessary.

"Also we found that you have required fields like checkinterval, retryinterval, notifperiod, checkperiod, etc. for hosttemplates but those fields are not required by nagios so Is there any way to remove that restriction when creating host templates ?" - place in a new issue if still wanted.
