### ISSUE TITLE
Synagios in combination with MailPlus server

### ISSUE THREAD

**Issue by florisi** [mclarkson/nagrestconf#63]
I'm running on a Synology DS716+ II MailPlus server with no problems.
DSM version DSM 6.0.2-8451 Update 2
After installing Synagios (0.14.5) I can't access the logfiles in MailPlus server anymore.

So I had to decide to uninstall your package, and that is a pitty.

**Comment by mclarkson** [comment]
Many thanks for reporting! It does 'steal' logs when it runs its own rsyslog, which it needs for the 'Logcheck: Messages' nagios check.

If you log into your diskstation over ssh then do:
```
vim /var/packages/Synagios/scripts/start-stop-status
```
and find the line (line 23):
```
    chroot . /etc/init.d/rsyslog start
```
and comment it out:
```
    #chroot . /etc/init.d/rsyslog start
```
Then your logs will not be stolen. Would you be able to try?

Thanks!

**Comment by florisi** [comment]
Hi Mark,

 

I’ve followed your instructions.

All works fine now.

 

Thanks.

 

Another question, is adding pictures to hosts also available in nagrest?

 

Regards,

 

Floris

 

Van: Mark Clarkson <notifications@github.com>
Beantwoorden - Aan: mclarkson/nagrestconf <reply@reply.github.com>
Datum: dinsdag 1 november 2016 13:54
Aan: mclarkson/nagrestconf <nagrestconf@noreply.github.com>
CC: florisi <floris.vaningen@isds.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [mclarkson/nagrestconf] Synagios in combination with MailPlus server (#63)

 

Many thanks for reporting! It does 'steal' logs when it runs its own rsyslog, which it needs for the 'Logcheck: Messages' nagios check.

If you log into your diskstation over ssh then do:
vim /var/packages/Synagios/scripts/start-stop-status
and find the line (line 23):
    chroot . /etc/init.d/rsyslog start
and comment it out:
    #chroot . /etc/init.d/rsyslog start
Then your logs will not be stolen. Would you be able to try?

Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mclarkson/nagrestconf","title":"mclarkson/nagrestconf","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mclarkson/nagrestconf"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mclarkson in #63: Many thanks for reporting! It does 'steal' logs when it runs its own rsyslog, which it needs for the 'Logcheck: Messages' nagios check.\r\n\r\nIf you log into your diskstation over ssh then do:\r\n```\r\nvim /var/packages/Synagios/scripts/start-stop-status\r\n```\r\nand find the line (line 23):\r\n```\r\n chroot . /etc/init.d/rsyslog start\r\n```\r\nand comment it out:\r\n```\r\n #chroot . /etc/init.d/rsyslog start\r\n```\r\nThen your logs will not be stolen. Would you be able to try?\r\n\r\nThanks!"}],"action":{"name":"View Issue","url":"https://github.com/mclarkson/nagrestconf/issues/63#issuecomment-257559334"}}}
