### ISSUE TITLE
Wrong timezone on web page

### ISSUE THREAD

**Issue by kickbit** [mclarkson/nagrestconf#64]
Hello!

It is an easy question for most of you, but I can not fix it.

My time on my Synology NAS is ok, but the time displayed on the Nagios 3.x web page is wrong. 

How can I fix it?
On the web page I see "Sat Dec 10 06:51:40 UTC 2016" 

sh-4.3# date
Sat Dec 10 07:51:03 CET 2016

Thank you for your help.
Best regards
   Kickbit

**Comment by mclarkson** [comment]
Please see issue #24. Thanks.
