### ISSUE TITLE
check_nrpe ssl issue on synology

### ISSUE THREAD

**Issue by svenerbe** [mclarkson/nagrestconf#65]
Hi,
i have a issue on my synology system. i have installed and configured the synagios pkg on my system.
But i have some issue  with the LD_LIBRARY_PATH.

when is try to run as nagios user the following:
nagios@svennas:/volume1/@appstore/Synagios/nagios-chroot/usr/lib/nagios/plugins$ ./check_nrpe -H 192.168.178.2 -c check_users
**./check_nrpe: /lib/libssl.so.1.0.0: no version information available (required by ./check_nrpe)**
USERS OK - 4 users currently logged in |users=4;5;10;0
nagios@svennas:/volume1/@appstore/Synagios/nagios-chroot/usr/lib/nagios/plugins$ export LD_LIBRARY_PATH=/volume1/@appstore/Synagios/nagios-chroot/usr/lib/x86_64-linux-gnu
nagios@svennas:/volume1/@appstore/Synagios/nagios-chroot/usr/lib/nagios/plugins$ ./check_nrpe -H 192.168.178.2 -c check_users
USERS OK - 4 users currently logged in |users=4;5;10;0

How can i set the LD_LIBRARY_PATH permanently?

**Comment by mclarkson** [comment]
Hi. You need to chroot into the nagios-chroot directory to test
commands. Cheers!

On Mon, 2017-01-02 at 08:14 -0800, svenerbe wrote:
> Hi,
> 
> > i have a issue on my synology system. i have installed and configured
the synagios pkg on my system.
> 
> But i have some issue  with the LD_LIBRARY_PATH.
> when is try to run as nagios user the following:
> 
> > > > nagios@svennas:/volume1/@appstore/Synagios/nagios-
chroot/usr/lib/nagios/plugins$ ./check_nrpe -H 192.168.178.2 -c
check_users
> 
> > ./check_nrpe: /lib/libssl.so.1.0.0: no version information available
(required by ./check_nrpe)
> 
> USERS OK - 4 users currently logged in |users=4;5;10;0
> 
> > > > nagios@svennas:/volume1/@appstore/Synagios/nagios-
chroot/usr/lib/nagios/plugins$ export LD_LIBRARY_PATH=/volume1/@appst
ore/Synagios/nagios-chroot/usr/lib/x86_64-linux-gnu
> 
> > > > nagios@svennas:/volume1/@appstore/Synagios/nagios-
chroot/usr/lib/nagios/plugins$ ./check_nrpe -H 192.168.178.2 -c
check_users
> 
> USERS OK - 4 users currently logged in |users=4;5;10;0
> How can i set the LD_LIBRARY_PATH permanently?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/mclarkson
/nagrestconf","title":"mclarkson/nagrestconf","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/mclarkson/nagrestconf"}},"updates":
{"snippets":[{"icon":"DESCRIPTION","message":"check_nrpe ssl issue on
synology (#65)"}],"action":{"name":"View
Issue","url":"https://github.com/mclarkson/nagrestconf/issues/65"}}}
