### ISSUE TITLE
Upgrading Nagios 3.5.1 to the latest on a Ubuntu system

### ISSUE THREAD

**Issue by btesoroni** [mclarkson/nagrestconf#71]
Are there any instructions on how to upgrade a Ubuntu system to the latest Nagios? The upgrade directions on the Nagios web site doesn't seem to work.

**Comment by mclarkson** [comment]
I think the easiest way is to use Centos 7!

**Comment by btesoroni** [comment]
Why is that?

**Comment by mclarkson** [comment]
Centos 7 has a fairly recent version of Nagios 4. It's managed by centos. It will have bug fix backported patches (I assume - like all other system packages). I don't know why nagios4 has never been packaged properly in debian or ubuntu but it's annoying.

So, using centos 7 instructions on nagrestconf web site you will get nagios 4.x, but not the latest nagios.

**Comment by mclarkson** [comment]
I want to see docker nagrestconf container which could use any docker nagios container really. That would be the way forward for me...

**Comment by mclarkson** [comment]
I have created docker containers for nagrestconf:

https://hub.docker.com/r/mclarkson/nagrestconf/
https://hub.docker.com/r/mclarkson/nagrestconf-restarter/

which work with a Nagios 4.3.2 container:

https://hub.docker.com/r/quantumobject/docker-nagios/

See: https://github.com/mclarkson/nagrestconf-docker

Very easy to install!
