### ISSUE TITLE
Upgrade Nagios 4.2.4 to 4.3.2

### ISSUE THREAD

**Issue by dadionysos** [mclarkson/nagrestconf#72]
Hello,

I would like to upgrade Nagios 4.2.4 to 4.3.2.  When I use the following link, it isn't working. What are the possibilities to upgrade to the latest version?

Thnx.

**Comment by mclarkson** [comment]
All I can say is that nagrestconf should work with Nagios 4.3.2, but I don't know for sure. Installing on a new machine would be safest of course using the nagrestconf gui to export and import the configuration.

Do you have any specific reason why you think it won't work after the upgrade?

**Comment by dadionysos** [comment]
This was the link I forgot to paste: https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/upgrading.html. It looks like it is installing Nagios on a different location. Will there be an easy installation package soon like the one I got from: https://sourceforge.net/projects/nagrestconf/files/Centos/Centos%207/. This was really easy to use. Thnx.

**Comment by mclarkson** [comment]
I'm thinking about putting nagrestconf in a docker image and getting it to work with any existing nagios docker image. I think this would be an accepted solution these days. Docker makes installing applications so simple. For example:

Google for docker nagios and the top link gives "Docker container for Nagios 4.3.2".
So installation would hopefully just be along the lines of:

```
docker run -d --name nagios -v /usr/local/nagios/etc -p 25 -p 80 quantumobject/docker-nagios
docker run --volumes-from nagios mclarkson/nagrestconf
```

Then you'd run some commands with 'docker exec' in nagrestconf, then you're good to go.
Something like that maybe.

**Comment by mclarkson** [comment]
I have created docker containers for nagrestconf:

https://hub.docker.com/r/mclarkson/nagrestconf/
https://hub.docker.com/r/mclarkson/nagrestconf-restarter/

which work with a Nagios 4.3.2 container:

https://hub.docker.com/r/quantumobject/docker-nagios/

See: https://github.com/mclarkson/nagrestconf-docker

Very easy to install!
