### ISSUE TITLE
restart_nagios

### ISSUE THREAD

**Issue by ahmadnl** [mclarkson/nagrestconf#73]
Hello Mark,
first i would like to sat thank you so much for your nice work and for all your help.
i have a issue with restart_nagios, when i use restart_nagios from the command line everything works as well, but if i only click on apply changes from nagrestconf interface nothing change on nagios until I restart him via <restart_nagios> or <service nagios restart>.

thank you,
Kind regards
Ahmad

**Comment by mclarkson** [comment]
Maybe you did not wait long enough for the cron job to run .. by default it runs every minute.

Or.. the the cron job is not running, see [the docs]([http://nagrestconf.smorg.co.uk/documentation/administration.php), you should have:
```
$ sudo su
# crontab -l
* * * * * /usr/bin/test -e /tmp/nagios_restart_request && ( /bin/rm /tmp/nagios_restart_request; /usr/bin/restart_nagios; )
```

and check your cron logs.

Or.. you're running CentOS 7 and you did not do the 'Configure the Operating System' section properly in the [docs](http://nagrestconf.smorg.co.uk/installguides/centos7.php)

If the above did not point you in the right direction please let me know your OS version.

**Comment by ahmadnl** [comment]
Thanks for your fast reaction,
my OS is debian 9.2 (stretch)
i am trying since 2 days i dont think thats something with waiting
`# crontab -l
* * * * * /usr/bin/test -e /tmp/nagios_restart_request && ( /bin/rm /tmp/nagios_restart_request; /usr/bin/restart_nagios; )
`
here is the last 2 lines from my corn log : 

Oct 12 13:42:01  CRON[21188]: (root) CMD (/usr/bin/test -e /tmp/nagios_restart_request && ( /bin/rm /tmp/nagios_restart_request; /usr/bin/restart_nagios; ))
Oct 12 13:43:01  CRON[21256]: (root) CMD (/usr/bin/test -e /tmp/nagios_restart_request && ( /bin/rm /tmp/nagios_restart_request; /usr/bin/restart_nagios; ))

**Comment by mclarkson** [comment]
I installed debian 9.2 and nagios3 isn't even in debian repos anymore, and nagrestconf will refuse to install without forcing it somehow. Debian recommends using icinga instead (see this [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846859)).

This might be a good time to try the [docker installation instructions](http://nagrestconf.smorg.co.uk/installguides/docker.php), which gives you the latest nagios with the latest nagrestconf.

If you want to fix this issue I think that you can work around the problem by changing the PrivateTmp setting in ` /lib/systemd/system/apache2.service` to 'PrivateTmp=false'.

**Comment by mclarkson** [comment]
I have updated the website to make it clear that docker should be used for Debian 9.x, so many thanks for your query!

**Comment by ahmadnl** [comment]
Thanks i have did this 
/lib/systemd/system/apache2.service to 'PrivateTmp=false'.
and its work now good !!!
thank you so much
i already usr your Docker container on other server and it's woks perfect without any issue/problem!
well doen

**Comment by mclarkson** [comment]
That's great! Thanks for reporting back, and you're welcome :)
