### ISSUE TITLE
Synagios 0.14.6 Installation failure on DS214play

### ISSUE THREAD

**Issue by coffeedave** [mclarkson/nagrestconf#74]
I've been trying to install synagios on 0.14.6 on a DS214play with DSM 6.1.3-15152 Update 8

The installation starts successfully in package manager, prompts for passwords etc, but then fails with message "Failed to Install Synagios"

In /var/log/synopkg.log we get the following error:

```
2017/10/28 14:51:06	upgrade Synagios 0.14.6 Begin postinst
sed: can't read nagios-chroot/etc/apache2/sites-enabled/000-default: No such file or directory
chroot: failed to run command '/bin/sh': Exec format error
```

Looking in the file system, the correct name for the file appears to have ".conf" on the end, e.g. nagios-chroot/etc/apache2/sites-enabled/000-default.conf

**Comment by mclarkson** [comment]
The `sed` error will not cause a problem and will not stop the system installing Synagios (Thanks for finding the error though!).

The "Exec format error" suggests that you managed to install the arm version on your ds14play, instead of the x86 version, but that shouldn't be possible. Did you use: synagios_0.14.6_jessie_x86.spk ?

Someone else installed on DS214play, see #45, but with synagios_0.14_jessie_repack_x86. If you did use  the 0.14.6 package above already then please try this older package to see if it works for you.

If the above does not help then please provide the output from `uname -a` and `echo $0` and `grep root /etc/passwd`. Thanks!

**Comment by mclarkson** [comment]
Oh, and please UNINSTALL the package first.

**Comment by coffeedave** [comment]
Thanks for the quick update!

Not knowing too much about the layout of the Synology NAS (I've not needed to telnet into it previously, though I'm fairly familiar with Linux) I was mostly just grepping recently updated log files for errors, which is how I found the issue above. If it's not going to stop the install I'll keep hunting as I'm sure there is a root cause logged somewhere :)

Package I used was synagios_0.14.6_jessie_x86.spk, I'll try now with the repack version and let you know the outcome.

Thanks!

**Comment by coffeedave** [comment]
Ok, we're further forward - the synagios_0.14_jessie_repack_x86.spk completes installation and starts, but I now have a different issue. When going to the http:<server>:8888/nagrestconf/ after loggin in I get the following permission error reported:

```
Could not execute query using REST.
  Please check system settings.

  REST return code: 400

  Error was:

  NAGCTL ERROR: Cannot write to /etc/nagios3/objects/local/.

```

I'll dig around a bit to see if I can resolve it, but in the meantime, to help with the original issue, here's the info you requested:

```
admin@Orca:/$ uname -a
Linux Orca 3.2.40 #15152 SMP PREEMPT Fri Oct 6 18:11:38 CST 2017 i686 GNU/Linux synology_evansport_214play
admin@Orca:/$ echo $0
-sh
admin@Orca:/$ grep root /etc/passwd
root:x:0:0:root:/root:/bin/ash
```

**Comment by coffeedave** [comment]
A quick chroot, and executing all the chown statements from the 14.6 post install script has resolved the permissions error - I'm now looking at what appears to be functioning homepage.

```
chown www-data:www-data /etc/nagios3/objects/local
chown -R www-data:www-data /etc/nagios3/objects/local/setup
chown -R www-data:www-data /etc/nagios3/objects/local/setup.known_good
chown www-data:root /run/lock/apache2
chown Debian-exim:Debian-exim /run/exim4
chown nagios:nagios /run/nagios3
chown www-data:www-data /usr/share/nagrestconf/htdocs/nagrestconf/download
chown -R www-data:www-data /usr/share/nagrestconf/htdocs/nagrestconf/upload
chown -R man:root /var/cache/man
chown www-data:www-data /var/cache/apache2/mod_cache_disk
chown nagios:www-data /var/cache/nagios3
chown nagios:nagios /var/lib/nagios3
chown nagios:nagios /var/lib/nagios3/spool
chown nagios:nagios /var/lib/nagios3/spool/checkresults
chown nagios:www-data /var/lib/nagios3/rw
chown nagios:nagios /var/lib/nagios
chown nagios:www-data /var/lib/pnp4nagios
chown -R nagios:nagios /var/lib/pnp4nagios/perfdata
chown -R Debian-exim:adm /var/log/exim4
chown nagios:adm /var/log/nagios3
chown -R nagios:adm /var/log/nagios3/archives
chown nagios:www-data /var/log/pnp4nagios
chown nagios:nagios /var/log/pnp4nagios/stats
chown Debian-exim:Debian-exim /var/spool/exim4
chown Debian-exim:Debian-exim /var/spool/exim4/db
chown Debian-exim:Debian-exim /var/spool/exim4/input
chown Debian-exim:Debian-exim /var/spool/exim4/msglog
chown nagios:nagios /var/spool/pnp4nagios
chown nagios:nagios /var/spool/pnp4nagios/npcd
chown nagios:nagios /var/spool/pnp4nagios/nagios
chown www-data:www-data /var/tmp/nagctl.output.tmp
chown root:mail /var/mail
```

I'll load up the template config and try it out.

**Comment by coffeedave** [comment]
After loading up the template config, I'm now up and running. Thanks for the help. Let me know if you need me to test out a new package or provide any additional info.

Cheers!

**Comment by mclarkson** [comment]
Nice one! Glad it worked. I have built a new package, 0.14.7, that should work on the DS214play. I had built a 64 bit version of the package for 0.14.6 and ds214play is 32 bit arch - doh!

**Comment by coffeedave** [comment]
I've just installed the 0.14.7 package and all went through smoothly, no errors. I'm now happily tracking my NAS and a host of other things.

Thanks for your help, and kudos for a great bit of software!

**Comment by mclarkson** [comment]
Great, many thanks for the feedback, and thanks for reporting!
