### ISSUE TITLE
event_handler

### ISSUE THREAD

**Issue by ahmadnl** [mclarkson/nagrestconf#75]
Hallo Mark,

i'm using Nagrestconf and i wanna use the event handler, do u have an idea how can i do that, i can't edit the service.cfg file because all changes will be overwritten .

thank you,
best regards,
Ahmad

**Comment by mclarkson** [comment]
Hi Ahmad,
You can use the REST api to add an event handler that will not be overwritten. See below for an example using the `ncrq` command.

Show an existing service:
```
$ ./nrcq http://127.0.0.1:8888/rest show/services --filter "svcdesc:NTP Time"

    name:diskstation
    template:svctmpl-lin
    command:check_ntp!-H 0.centos.pool.ntp.org -w 0.5 -c 1.0
    svcdesc:NTP Time
    activechecks:1
```
Add an event handler. Nagrestconf does not check that the command exists so an invalid configuration can be made :(
```
$ ./nrcq http://127.0.0.1:8888/rest modify/services \
    -d name:diskstation \
    -d "svcdesc:NTP Time" \
    -d eventhandler:restart_ntp
SUCCESS
```
Show the service again:
```
$ ./nrcq http://127.0.0.1:8888/rest show/services --filter "svcdesc:NTP Time"

    name:diskstation
    template:svctmpl-lin
    command:check_ntp!-H 0.centos.pool.ntp.org -w 0.5 -c 1.0
    svcdesc:NTP Time
    activechecks:1
    eventhandler:restart_ntp
```
I **can** change settings in the GUI, for example, I changed the `checkinterval` in the GUI and the eventhandler has remained (even though you can't see it in the GUI):
```
# ./nrcq http://127.0.0.1:8888/rest show/services -f "svcdesc:NTP Time"

    name:diskstation
    template:svctmpl-lin
    command:check_ntp!-H 0.centos.pool.ntp.org -w 0.5 -c 1.0
    svcdesc:NTP Time
    activechecks:1
    disable:0
    checkinterval:3
    eventhandler:restart_ntp
```
I then applied the changes in the GUI.

HTH
Mark.

**Comment by mclarkson** [comment]
Closing due to no response. Please re-open if you need more info.
