### ISSUE TITLE
pnp4nagios not found

### ISSUE THREAD

**Issue by AlfaJackal** [mclarkson/nagrestconf#82]
Installed Synagios and Nagrestconfig as instructed via docker guide. Both are running fine on my Synology. 

Unfortunately, the graph does not work:
„pnp4nagios/index.php/graph was not found on this server“

Can anybody help?

**Comment by mclarkson** [comment]
If you installed using the docker guide then pnp4nagios will not be installed. Only the Synology package has it bundled with the installation.
