### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by AlfaJackal** [mclarkson/nagrestconf#86]
Hi,

unfortunately I forgot my password for logging in on http://diskstation:8888/nagrestconf/ and http://diskstation:8888/nagios3

Of course I do have access to my diskstation admin account and console. Where do I find the credentials so that I can change it?

**Comment by mclarkson** [comment]
Log into the diskstation over ssh. chroot into the nagios system, something like:
```
chroot /volume1/@appstore/Synagios/nagios-chroot /bin/bash
```
Probably followed by something like:
```
htpasswd /etc/nagios3/htpasswd.users nagiosadmin
htpasswd /etc/nagios3/htpasswd.users nagrestconfadmin
```

Something along those lines. Don't just type the above in without thinking about it as it probably won't work, but should be as simple as that. Sorry, but I don't have a synology device anymore (well it's boxed away). Good luck!
