### ISSUE TITLE
notification by email

### ISSUE THREAD

**Issue by hestiap** [mclarkson/nagrestconf#90]
hello,
I've Nagios on a Synology NAS (Synagios) that used Server Mail to send email notifications. This no longer works :-(
I've had an opened issue with Synology support since more than one month with no hope to get an outcome...
I'd like to set a custom notification with something like:
curl --url 'smtps://smtp.xxx.fr:465' --ssl-reqd --mail-from ...
It works well in command line.
In nagrestconf I've changed the "notify-host-by-email" with another command. But nothing happened :-(
I've tried simple commands like /bin/touch /tmp/toto and nothing... even though I saw things in log

ZZtest3 | N/A | HOST DOWN | 2021-01-08 13:09:52 | ds-admin | notify-host-by-email | check_ping: Invalid hostname/address 

[2021-01-08 13:09:52] HOST NOTIFICATION: ds-admin;ZZtest3;DOWN;notify-host-by-email;check_ping: Invalid hostname/address - ZZtest3

Could you help me to get the change works in the notify-host-by-email?

**Comment by hestiap** [comment]
I've found my mistake...
the directory for Synagios is /volume1/@appstore/Synagios/nagios-chroot/home
so I need to look at /volume1/@appstore/Synagios/nagios-chroot/tmp

**Comment by mclarkson** [comment]
Great! Glad you found it!
